source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in form_builder.gemspec.
gemspec

group :development do
  gem 'annotate', '~> 3.1', '>= 3.1.1'
  gem 'pg'
end

gem 'dry-monads', '~> 1.4'
gem 'dry-rails', '~> 0.3.0'
gem 'dry-struct', '~> 1.4'

# To use a debugger
# gem 'byebug', group: [:development, :test]
